"""phase4 qds schema

Revision ID: 4f767890ce95
Revises: b16f116feb2f
Create Date: 2026-03-12 14:44:01.417596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f767890ce95'
down_revision: Union[str, Sequence[str], None] = 'b16f116feb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qds_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('qds_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('review_state', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['qds_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qds_deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('deployed_by', sa.String(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['qds_assets.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['qds_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qds_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('entry_step_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['qds_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qds_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('qualification_status', sa.Enum('high_fit', 'medium_fit', 'low_fit', 'not_qualified', name='qds_qualification_status_enum'), nullable=False),
    sa.Column('score_band_min', sa.Float(), nullable=True),
    sa.Column('score_band_max', sa.Float(), nullable=True),
    sa.Column('routing_target', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['qds_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qds_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.Enum('single_select', 'multi_select', 'text_input', 'numeric_input', 'yes_no', 'informational', 'terminal_outcome', name='qds_step_type_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['qds_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qds_scoring_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('answer_value', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['qds_flows.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['qds_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qds_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='qds_session_status_enum'), nullable=True),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('cumulative_score', sa.Float(), nullable=True),
    sa.Column('outcome_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('device_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['qds_assets.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['qds_flows.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['qds_outcomes.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['qds_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qds_sessions_session_key'), 'qds_sessions', ['session_key'], unique=False)
    op.create_table('qds_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('from_step_id', sa.UUID(), nullable=False),
    sa.Column('to_step_id', sa.UUID(), nullable=True),
    sa.Column('to_outcome_id', sa.UUID(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['qds_flows.id'], ),
    sa.ForeignKeyConstraint(['from_step_id'], ['qds_steps.id'], ),
    sa.ForeignKeyConstraint(['to_outcome_id'], ['qds_outcomes.id'], ),
    sa.ForeignKeyConstraint(['to_step_id'], ['qds_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qds_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('answer_value', sa.JSON(), nullable=False),
    sa.Column('score_contribution', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['qds_sessions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['qds_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: Alembic detected orphan 'assets' table — intentionally not dropping it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qds_answers')
    op.drop_table('qds_transitions')
    op.drop_index(op.f('ix_qds_sessions_session_key'), table_name='qds_sessions')
    op.drop_table('qds_sessions')
    op.drop_table('qds_scoring_rules')
    op.drop_table('qds_steps')
    op.drop_table('qds_outcomes')
    op.drop_table('qds_flows')
    op.drop_table('qds_deployments')
    op.drop_table('qds_versions')
    op.drop_table('qds_assets')
    # ### end Alembic commands ###
